services: 
  sqlite: 
    image: nouchka/sqlite3  
    container_name: 'db-shooper'
    volumes:
      - sqlite-data:/db  
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    entrypoint: ["sh", "-c", "sqlite3 /db/database.db < /docker-entrypoint-initdb.d/init.sql && tail -f /dev/null"]
    restart: always

  api: 
    build: .
    ports:
      - "3000:3000"
    volumes: 
      - ./app:/usr/src/app
      - sqlite-data:/usr/src/app/db
    depends_on:
      - sqlite 
    restart: always
    
volumes:
  sqlite-data:
